spring.datasource.url=jdbc:postgresql://localhost:5432/discount_market
spring.datasource.username=discount_app
spring.datasource.password=discount_app_password
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

scrapers.scrapy.max-pages=1
